version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:00"

  - package-ecosystem: "gomod"
    allow:
      - dependency-type: "direct"
        update-type: "semver-minor"
      - dependency-type: "direct"
        update-type: "semver-major"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:00"
    ignore:
      - dependency-name: "github.com/onflow/flow-go"
      - dependency-name: "github.com/onflow/cadence"
      - dependency-name: "github.com/onflow/crypto"
      - dependency-name: "github.com/onflow/flow-go-sdk"
