name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

env:
  GO_VERSION: '1.21'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run tests
        run: |
          make install-tools
          make generate
          make test
          make coverage 
          make check-tidy
          make check-headers
          make check-schema
      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.txt
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: generate
        run: make generate
      - uses: golangci/golangci-lint-action@v5.1.0
        with:
          args: --timeout=3m
          skip-pkg-cache: true
